### ISSUE TITLE
PowerDown button (readAD) fails if power level is at threshold X

### ISSUE THREAD

**Issue by seclorum** [magicshifter/MS3000-Firmware#1]
.. where threshold X is something like 3.x volts (i.e. should be enough voltage to readAD).

This has the net effect that the PowerDown button no longer works when it is needed most: when the user should turn off the device.  This creates a current usability issue, so this bug is critical.

This usability issue could be addressed by adding a 'low-power' UI mode, which the 'shifter switches to when the power level is 'very low' (e.g. threshold X+0.5%), indicating that the user should plug in the 'shifter for charging.  When the cable is plugged back in, the 'low-power' UI mode is switched out, back to normal mode.  If, after some seconds (e.g. 20), the power is not plugged back in, the low-power UI mode shuts the shifter off automatically.

Another fix might be to not use the middle power button for the power down UI event - i.e. switch Power with Button B (button closer to the cable input).  This way, no matter what (assumedly), we can get a power-down button event from the user, even if we are in ultra-low power mode.

Ultra-low-power-UI mode (as described), could be implemented as a simple sub-mode which will blink, then power off the 'shifter, unless power goes back up.  Estimate time to implement: 1 hour.

**Comment by wizard23** [comment]
Only happens on some shifters since the internal adc reference seems to vary from ESP to ESP
in the code:

bool powerButtonPressed(void) {
    // had unusual high values on one of the 100x PCBs so this threshold is bigger now
    return analogRead(A0) > 970;
}
I changed that in https://github.com/magicshifter/MS3000-Firmware/commit/2b0c39bdabc400d63b63ba9d2e8c6ce29050e54e
because I had a shifter that has a value > 950 even if no button is pressed at all. I fear we need some kind of adaptive logic that tries to determine this threshold by looking at the changes.

so we have some shifterst that have values higher than

**Comment by seclorum** [comment]
Okay, I added the LowPowerEmergencyMode UI .. please check out my commit to master.  Search for MIN_POWER_LEVEL_THRESHOLD and you will see the entry point.  If we go lower than this threshold during Button Timer, we enter PowerEmergency mode, which functions as described.  

TODO: Adjust MIN_POWER_LEVEL_THRESHOLD.

**Comment by seclorum** [comment]
Okay, looked into this a bit more .. Very interesting articles here:

http://www.esp8266-projects.com/2015/03/internal-adc-esp8266.html
http://www.esp8266-projects.com/2016/03/esp8266-adc-input-frontend.html

We could run their Logger application a couple of the factory-shifter variants that you have discovered might have different values?

**Comment by wizard23** [comment]
I have two now that show the behaviour :) will test your commit asap.

**Comment by seclorum** [comment]
Please note: its only a low-power UI.  The real magic is in calculating the factorial for the variant shifters, and/or otherwise detecting them at bootup/callibrating for it.  esp8266-projects.com seems to provide insights, but you know the circuitry better than me.  So I humbly await further input.

**Comment by wizard23** [comment]
Jay and I fixed this for 1.2! :)
