### ISSUE TITLE
2.0 release prebuild 4MB image

### ISSUE THREAD

**Issue by wizard23** [magicshifter/MS3000-Firmware#11]
What are we waiting for? ;)

**Comment by seclorum** [comment]
I've tried to document the Issues that this depends on with the "MS3KOS2.0" tag, so the answer is, anything with that tag...

**Comment by seclorum** [comment]
@wizard23 

Issues documented here:

https://github.com/magicshifter/MS3000/issues

**Comment by wizard23** [comment]
release early release often...which of this issues is a show stopper?
last release was Jun 17, 2016

**Comment by wizard23** [comment]
call it 1.9 if thats bettter for u ;)

**Comment by seclorum** [comment]
Check the MS3KOS2.0 tags, these are what I consider we should fix before we release 2.0.
