### ISSUE TITLE
base64_decode() not declared

### ISSUE THREAD

**Issue by kintel** [magicshifter/MS3000-Firmware#6]
This is probably related to PlatformIO 3.x:

There's a file in PlatformIO (`.platformio/packages/framework-arduinoespressif8266/cores/esp8266/base64.h`) which overrides a file in the firmware (`MS3KOS/lib/Base64/Base64.h`), but only for non-case-sensitive file systems.

The easy workaround is to simply rename the local file.
A better solution might be to require PlatformIO 3.x and port to their base64 implementation.

**Comment by seclorum** [comment]
Fixed as of 2.0.
