### ISSUE TITLE
Default Vaulues for P-HIgh and P-LOw are wasting battery

### ISSUE THREAD

**Issue by wizard23** [magicshifter/MS3000-Firmware#8]
I think it would be best if:

P-HI: 10min
P-LO: 5min

would be a good reason to release 1.3.2 don't you think so too? ;)

kthnx! :)

**Comment by seclorum** [comment]
Will address sysPref and userPref persistence soon.

**Comment by seclorum** [comment]
(and yay: working on 2.0!)

**Comment by seclorum** [comment]
This is implemented in MS3KOS2.0, so .. closing ..
